### ISSUE TITLE
Social block not showing

### ISSUE THREAD

**Issue by obenn** [gethugothemes/navigator-hugo#43]
As can be seen in the demo here: https://demo.themefisher.com/navigator-hugo/en/contact/

The address and phone blocks show up, but not the social block. The html is there, but it is invisible.

I am using the latest safari. It does show up on mobile resolutions.

<img width="1357" alt="Screen Shot 2021-01-03 at 1 28 53 PM" src="https://user-images.githubusercontent.com/14519745/103485881-a1019c00-4dc7-11eb-879f-5a9b8207a292.png">

**Comment by somratpro** [comment]
Hello @obenn 

I checked it on a safari browser, and everything is loading correctly. you may try to clear your browser cache. thank you

**Comment by obenn** [comment]
Cleared cache and tried again on iPhone, iPad Pro and MacBook. Only showing the social block on iPhone. Changed network as well, no content blockers either.

**Comment by divinerites** [comment]
works fine here too ..Safari 14.0.2



<img width="623" alt="Capture d’écran 2021-01-10 à 09 20 27" src="https://user-images.githubusercontent.com/32342823/104117923-41eeda80-5325-11eb-91cb-f4c9eaf79a89.png">

**Comment by obenn** [comment]
My bad, it was indeed the extension "1Blocker".
