### ISSUE TITLE
Submenu dropdown on mobile not displayed correctly 

### ISSUE THREAD

**Issue by lisaschelch** [gethugothemes/navigator-hugo#46]
Hello!

There's an issue with the dropdown submenu on mobile. The dropdown is collapsed but won't display the content and won't toggle if it gets activated.  I figured out that the display:block in the style.css (.navigation .dropdown .dropdown-menu) overwrites the display in the bootstrap collapse function. If I remove the display:block it works fine on mobile but then the hover of the submenu on desktop doesn't work anymore (only on click). Can you tell me how to solve this issue?

thx br

<img width="329" alt="Screenshot 2021-02-25 at 14 50 36" src="https://user-images.githubusercontent.com/77283579/109163603-c97b9600-7779-11eb-8dc3-7754cd14ac15.png">
<img width="333" alt="Screenshot 2021-02-25 at 14 50 46" src="https://user-images.githubusercontent.com/77283579/109163611-cb455980-7779-11eb-94e9-9e3c4cdb2b16.png">

Lisa

**Comment by sojonatgithub** [comment]
Hey @lisaschelch
You have to write code on responsive media query
```
@media (min-width:991px) {
  .dropdown-menu {
    display: block;
    opacity: 0;
    visibility: hidden;
    width: 220px;
    transition: 0.2s;
    left: 50%;
    border-radius: 8px;
    transform: translate(-50%, 15px);
  }

  .dropdown:hover .dropdown-menu {
    opacity: 1;
    visibility: visible;
    box-shadow: 0 10px 30px rgba(22, 28, 45, .10);
    transform: translate(-50%, -6px);
  }
}
```

**Comment by lisaschelch** [comment]
Thanks for the reply. Unfortunately that did not solve the problem. I removed the display: block; from the dropdown. At least it looks good then. You just have to click the nav item on desktop to show up. But that's better than those gaps in the mobile menu.
