### ISSUE TITLE
Formating of rmarkdown files

### ISSUE THREAD

**Issue by mcoshima** [gethugothemes/navigator-hugo#47]
Hi I really like your theme but I noticed that when I add a blog post as an Rmarkdown file, the formatting is not great. There are large blocks of space between text blocks and new headers. Is there a way to fix this? 

<img width="770" alt="Screen Shot 2021-03-02 at 9 30 38 AM" src="https://user-images.githubusercontent.com/20287351/109663338-fcd37180-7b39-11eb-95bc-5d8ef8541560.png">

If I use just a markdown file it formats fine but since I want to be able to insert and run code, I would like to use .rmarkdown files.
Thanks, 
Meg

**Comment by somratpro** [comment]
Hello @mcoshima 
Maybe this content can help you out https://zurich-r-user-group.github.io/slides/20180903_blogdown_rmeetup_tlorusso.pdf
