### ISSUE TITLE
Loading page after files are public

### ISSUE THREAD

**Issue by Brantlab** [gethugothemes/navigator-hugo#52]
I can run hugo server and the site looks great. If I run hugo and get the html files I just get spinning screen whether on webserver or local. 

Start building sites …
hugo v0.88.1-5BC54738 windows/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio

                   | EN
-------------------+-----
  Pages            | 40
  Paginator pages  |  1
  Non-page files   |  0
  Static files     | 95
  Processed images |  0
  Aliases          |  5
  Sitemaps         |  1
  Cleaned          |  0

Total in 17149 ms

**Comment by mehedi-sharif** [comment]
Hey @Brantlab ,
Thanks for using our theme. It seems that you already compiled the Hugo files. Can you please indicate what issue you are facing here? Is it the spinning issue or anything else? Sometimes a video can give us a deep understanding about the issue ( use loom.com and create a video )
Thanks

**Comment by Brantlab** [comment]
Actually turning cookies off  in the config.toml fixed my issue
\`# cookies
[params.cookies]
enable = false
expire_days = 2`

The site would come up and just act like it was loading

**Comment by mehedi-sharif** [comment]
Good to know that your issue has been fixed . May I know where you are using this theme(Domain) . And why you choose this theme ?
Also would be grateful if you put a star in this repo. 
Thanks
