### ISSUE TITLE
pre-loading screen not close when reload on mobile IOS

### ISSUE THREAD

**Issue by najgit** [gethugothemes/navigator-hugo#53]
When the first load is successful. then when does the page reload action the loading screen is blocking the contents (not close).
Using on iPhone 13, and the loading screen is closed when clear the site cache.

**Comment by najgit** [comment]
sorry, forget to mention the theme use. I use "Sassis" theme build with "hugo --minify"

**Comment by tfsomrat** [comment]
Hello @najgit 

I didn't understand you properly. If you are using sassis theme, then why did you create an issue in this theme. please explain a little bit.

**Comment by najgit** [comment]
Sorry I cannot find the sassis git to open the issue, appreciate if you can provide me

**Comment by tfsomrat** [comment]
Hello @najgit 

please contact here for your support https://gethugothemes.com/contact/
